// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: api/ocp-video-api/ocp-video-api.proto

package oct_video_api

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListVideosV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit  uint64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset uint64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *ListVideosV1Request) Reset() {
	*x = ListVideosV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_video_api_ocp_video_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListVideosV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVideosV1Request) ProtoMessage() {}

func (x *ListVideosV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_video_api_ocp_video_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVideosV1Request.ProtoReflect.Descriptor instead.
func (*ListVideosV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_video_api_ocp_video_api_proto_rawDescGZIP(), []int{0}
}

func (x *ListVideosV1Request) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListVideosV1Request) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListVideosV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Videos []*Video `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
}

func (x *ListVideosV1Response) Reset() {
	*x = ListVideosV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_video_api_ocp_video_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListVideosV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVideosV1Response) ProtoMessage() {}

func (x *ListVideosV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_video_api_ocp_video_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVideosV1Response.ProtoReflect.Descriptor instead.
func (*ListVideosV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_video_api_ocp_video_api_proto_rawDescGZIP(), []int{1}
}

func (x *ListVideosV1Response) GetVideos() []*Video {
	if x != nil {
		return x.Videos
	}
	return nil
}

type CreateVideoV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SlideId     uint64 `protobuf:"varint,1,opt,name=slide_id,json=slideId,proto3" json:"slide_id,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *CreateVideoV1Request) Reset() {
	*x = CreateVideoV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_video_api_ocp_video_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateVideoV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVideoV1Request) ProtoMessage() {}

func (x *CreateVideoV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_video_api_ocp_video_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVideoV1Request.ProtoReflect.Descriptor instead.
func (*CreateVideoV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_video_api_ocp_video_api_proto_rawDescGZIP(), []int{2}
}

func (x *CreateVideoV1Request) GetSlideId() uint64 {
	if x != nil {
		return x.SlideId
	}
	return 0
}

func (x *CreateVideoV1Request) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateVideoV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoId uint64 `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
}

func (x *CreateVideoV1Response) Reset() {
	*x = CreateVideoV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_video_api_ocp_video_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateVideoV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVideoV1Response) ProtoMessage() {}

func (x *CreateVideoV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_video_api_ocp_video_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVideoV1Response.ProtoReflect.Descriptor instead.
func (*CreateVideoV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_video_api_ocp_video_api_proto_rawDescGZIP(), []int{3}
}

func (x *CreateVideoV1Response) GetVideoId() uint64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type RemoveVideoV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoId uint64 `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
}

func (x *RemoveVideoV1Request) Reset() {
	*x = RemoveVideoV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_video_api_ocp_video_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveVideoV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveVideoV1Request) ProtoMessage() {}

func (x *RemoveVideoV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_video_api_ocp_video_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveVideoV1Request.ProtoReflect.Descriptor instead.
func (*RemoveVideoV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_video_api_ocp_video_api_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveVideoV1Request) GetVideoId() uint64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type RemoveVideoV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Found bool `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
}

func (x *RemoveVideoV1Response) Reset() {
	*x = RemoveVideoV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_video_api_ocp_video_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveVideoV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveVideoV1Response) ProtoMessage() {}

func (x *RemoveVideoV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_video_api_ocp_video_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveVideoV1Response.ProtoReflect.Descriptor instead.
func (*RemoveVideoV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_video_api_ocp_video_api_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveVideoV1Response) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type DescribeVideoV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoId uint64 `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
}

func (x *DescribeVideoV1Request) Reset() {
	*x = DescribeVideoV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_video_api_ocp_video_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeVideoV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeVideoV1Request) ProtoMessage() {}

func (x *DescribeVideoV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_video_api_ocp_video_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeVideoV1Request.ProtoReflect.Descriptor instead.
func (*DescribeVideoV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_video_api_ocp_video_api_proto_rawDescGZIP(), []int{6}
}

func (x *DescribeVideoV1Request) GetVideoId() uint64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type DescribeVideoV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Video *Video `protobuf:"bytes,1,opt,name=video,proto3" json:"video,omitempty"`
}

func (x *DescribeVideoV1Response) Reset() {
	*x = DescribeVideoV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_video_api_ocp_video_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeVideoV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeVideoV1Response) ProtoMessage() {}

func (x *DescribeVideoV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_video_api_ocp_video_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeVideoV1Response.ProtoReflect.Descriptor instead.
func (*DescribeVideoV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_video_api_ocp_video_api_proto_rawDescGZIP(), []int{7}
}

func (x *DescribeVideoV1Response) GetVideo() *Video {
	if x != nil {
		return x.Video
	}
	return nil
}

// Описание видео
type Video struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SlideId uint64 `protobuf:"varint,2,opt,name=slide_id,json=slideId,proto3" json:"slide_id,omitempty"`
	Link    string `protobuf:"bytes,3,opt,name=link,proto3" json:"link,omitempty"`
}

func (x *Video) Reset() {
	*x = Video{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_video_api_ocp_video_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_video_api_ocp_video_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_api_ocp_video_api_ocp_video_api_proto_rawDescGZIP(), []int{8}
}

func (x *Video) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Video) GetSlideId() uint64 {
	if x != nil {
		return x.SlideId
	}
	return 0
}

func (x *Video) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

var File_api_ocp_video_api_ocp_video_api_proto protoreflect.FileDescriptor

var file_api_ocp_video_api_ocp_video_api_proto_rawDesc = []byte{
	0x0a, 0x25, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x2d,
	0x61, 0x70, 0x69, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x2d, 0x61, 0x70,
	0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6f, 0x63, 0x70, 0x2e, 0x76, 0x69, 0x64,
	0x65, 0x6f, 0x2e, 0x61, 0x70, 0x69, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x43, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x73, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x44, 0x0a, 0x14,
	0x4c, 0x69, 0x73, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x76, 0x69, 0x64, 0x65, 0x6f,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x06, 0x76, 0x69, 0x64, 0x65,
	0x6f, 0x73, 0x22, 0x53, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x6c,
	0x69, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x73, 0x6c,
	0x69, 0x64, 0x65, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x32, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x19, 0x0a, 0x08, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x07, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x22, 0x3a, 0x0a, 0x14, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x08, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x32, 0x02, 0x20, 0x00, 0x52, 0x07,
	0x76, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x22, 0x2d, 0x0a, 0x15, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x22, 0x3c, 0x0a, 0x16, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x22, 0x0a, 0x08, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x32, 0x02, 0x20, 0x00, 0x52, 0x07, 0x76, 0x69, 0x64,
	0x65, 0x6f, 0x49, 0x64, 0x22, 0x45, 0x0a, 0x17, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x56, 0x69, 0x64, 0x65, 0x6f, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2a, 0x0a, 0x05, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x52, 0x05, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x22, 0x46, 0x0a, 0x05, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x6c, 0x69, 0x64, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x73, 0x6c, 0x69, 0x64, 0x65, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c,
	0x69, 0x6e, 0x6b, 0x32, 0xe6, 0x03, 0x0a, 0x0b, 0x4f, 0x63, 0x70, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x41, 0x70, 0x69, 0x12, 0x6b, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x73, 0x56, 0x31, 0x12, 0x22, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x56, 0x31,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x76, 0x69,
	0x64, 0x65, 0x6f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x73, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x12, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x0c, 0x12, 0x0a, 0x2f, 0x76, 0x31, 0x2f, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x73,
	0x12, 0x7f, 0x0a, 0x0f, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x56, 0x31, 0x12, 0x25, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x6f, 0x63, 0x70,
	0x2e, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17, 0x12, 0x15, 0x2f, 0x76, 0x31, 0x2f,
	0x76, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x2f, 0x7b, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x69, 0x64,
	0x7d, 0x12, 0x6e, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x56, 0x31, 0x12, 0x23, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x56, 0x31,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x76, 0x69,
	0x64, 0x65, 0x6f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x12, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x0c, 0x22, 0x0a, 0x2f, 0x76, 0x31, 0x2f, 0x76, 0x69, 0x64, 0x65, 0x6f,
	0x73, 0x12, 0x79, 0x0a, 0x0d, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x56, 0x31, 0x12, 0x23, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x56, 0x31,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x76, 0x69,
	0x64, 0x65, 0x6f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1d, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x17, 0x2a, 0x15, 0x2f, 0x76, 0x31, 0x2f, 0x76, 0x69, 0x64, 0x65, 0x6f,
	0x73, 0x2f, 0x7b, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x69, 0x64, 0x7d, 0x42, 0x2f, 0x5a, 0x2d,
	0x6f, 0x63, 0x70, 0x2d, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x2d, 0x61, 0x70, 0x69, 0x3b,
	0x6f, 0x63, 0x74, 0x5f, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_ocp_video_api_ocp_video_api_proto_rawDescOnce sync.Once
	file_api_ocp_video_api_ocp_video_api_proto_rawDescData = file_api_ocp_video_api_ocp_video_api_proto_rawDesc
)

func file_api_ocp_video_api_ocp_video_api_proto_rawDescGZIP() []byte {
	file_api_ocp_video_api_ocp_video_api_proto_rawDescOnce.Do(func() {
		file_api_ocp_video_api_ocp_video_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_ocp_video_api_ocp_video_api_proto_rawDescData)
	})
	return file_api_ocp_video_api_ocp_video_api_proto_rawDescData
}

var file_api_ocp_video_api_ocp_video_api_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_ocp_video_api_ocp_video_api_proto_goTypes = []interface{}{
	(*ListVideosV1Request)(nil),     // 0: ocp.video.api.ListVideosV1Request
	(*ListVideosV1Response)(nil),    // 1: ocp.video.api.ListVideosV1Response
	(*CreateVideoV1Request)(nil),    // 2: ocp.video.api.CreateVideoV1Request
	(*CreateVideoV1Response)(nil),   // 3: ocp.video.api.CreateVideoV1Response
	(*RemoveVideoV1Request)(nil),    // 4: ocp.video.api.RemoveVideoV1Request
	(*RemoveVideoV1Response)(nil),   // 5: ocp.video.api.RemoveVideoV1Response
	(*DescribeVideoV1Request)(nil),  // 6: ocp.video.api.DescribeVideoV1Request
	(*DescribeVideoV1Response)(nil), // 7: ocp.video.api.DescribeVideoV1Response
	(*Video)(nil),                   // 8: ocp.video.api.Video
}
var file_api_ocp_video_api_ocp_video_api_proto_depIdxs = []int32{
	8, // 0: ocp.video.api.ListVideosV1Response.videos:type_name -> ocp.video.api.Video
	8, // 1: ocp.video.api.DescribeVideoV1Response.video:type_name -> ocp.video.api.Video
	0, // 2: ocp.video.api.OcpVideoApi.ListVideosV1:input_type -> ocp.video.api.ListVideosV1Request
	6, // 3: ocp.video.api.OcpVideoApi.DescribeVideoV1:input_type -> ocp.video.api.DescribeVideoV1Request
	2, // 4: ocp.video.api.OcpVideoApi.CreateVideoV1:input_type -> ocp.video.api.CreateVideoV1Request
	4, // 5: ocp.video.api.OcpVideoApi.RemoveVideoV1:input_type -> ocp.video.api.RemoveVideoV1Request
	1, // 6: ocp.video.api.OcpVideoApi.ListVideosV1:output_type -> ocp.video.api.ListVideosV1Response
	7, // 7: ocp.video.api.OcpVideoApi.DescribeVideoV1:output_type -> ocp.video.api.DescribeVideoV1Response
	3, // 8: ocp.video.api.OcpVideoApi.CreateVideoV1:output_type -> ocp.video.api.CreateVideoV1Response
	5, // 9: ocp.video.api.OcpVideoApi.RemoveVideoV1:output_type -> ocp.video.api.RemoveVideoV1Response
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_ocp_video_api_ocp_video_api_proto_init() }
func file_api_ocp_video_api_ocp_video_api_proto_init() {
	if File_api_ocp_video_api_ocp_video_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_ocp_video_api_ocp_video_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListVideosV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_video_api_ocp_video_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListVideosV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_video_api_ocp_video_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateVideoV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_video_api_ocp_video_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateVideoV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_video_api_ocp_video_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveVideoV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_video_api_ocp_video_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveVideoV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_video_api_ocp_video_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeVideoV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_video_api_ocp_video_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeVideoV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_video_api_ocp_video_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Video); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_ocp_video_api_ocp_video_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ocp_video_api_ocp_video_api_proto_goTypes,
		DependencyIndexes: file_api_ocp_video_api_ocp_video_api_proto_depIdxs,
		MessageInfos:      file_api_ocp_video_api_ocp_video_api_proto_msgTypes,
	}.Build()
	File_api_ocp_video_api_ocp_video_api_proto = out.File
	file_api_ocp_video_api_ocp_video_api_proto_rawDesc = nil
	file_api_ocp_video_api_ocp_video_api_proto_goTypes = nil
	file_api_ocp_video_api_ocp_video_api_proto_depIdxs = nil
}
